// Vercel Serverless Function Endpoint for SONIQX Send Email Report (/api/send-email)
const nodemailer = require('nodemailer');
const fs = require('fs');
const path = require('path');

const CONFIG_PATH = path.join(__dirname, '..', 'email_config.json');

function getSMTPConfig() {
    let config = {
        smtp_service: 'gmail',
        smtp_host: process.env.SMTP_HOST || 'smtp.gmail.com',
        smtp_port: parseInt(process.env.SMTP_PORT || '465', 10),
        smtp_secure: true,
        smtp_user: process.env.SMTP_USER || '',
        smtp_pass: process.env.SMTP_PASS || ''
    };

    if (fs.existsSync(CONFIG_PATH)) {
        try {
            const fileData = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
            config = { ...config, ...fileData };
        } catch (err) {}
    }

    if (process.env.SMTP_USER) config.smtp_user = process.env.SMTP_USER;
    if (process.env.SMTP_PASS) config.smtp_pass = process.env.SMTP_PASS;
    if (process.env.SMTP_HOST) config.smtp_host = process.env.SMTP_HOST;
    if (process.env.SMTP_PORT) config.smtp_port = parseInt(process.env.SMTP_PORT, 10);

    return config;
}

function createTransporter(config) {
    if (config.smtp_service === 'gmail') {
        return nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: config.smtp_user,
                pass: config.smtp_pass
            }
        });
    }

    return nodemailer.createTransport({
        host: config.smtp_host || 'smtp.gmail.com',
        port: config.smtp_port || 465,
        secure: config.smtp_secure !== undefined ? config.smtp_secure : true,
        auth: {
            user: config.smtp_user,
            pass: config.smtp_pass
        }
    });
}

module.exports = async function handler(req, res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') {
        return res.status(204).end();
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    try {
        const bodyData = typeof req.body === 'string' ? JSON.parse(req.body) : (req.body || {});
        const {
            recipientEmail,
            userName = 'Patient',
            reportId = 'SHS-2026-9041',
            date = new Date().toLocaleDateString(),
            overallStatus = 'PASS',
            notes = '',
            pdfBase64,
            fileName
        } = bodyData;

        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!recipientEmail || typeof recipientEmail !== 'string' || !emailRegex.test(recipientEmail.trim())) {
            return res.status(400).json({
                success: false,
                error: `Invalid email address format: "${recipientEmail || ''}". Please enter a valid email address.`
            });
        }

        const cleanRecipient = recipientEmail.trim();

        if (!pdfBase64) {
            return res.status(400).json({
                success: false,
                error: 'Missing PDF report data. Unable to generate attachment.'
            });
        }

        let cleanBase64 = pdfBase64;
        if (cleanBase64.includes(',')) {
            cleanBase64 = cleanBase64.split(',')[1];
        }
        const pdfBuffer = Buffer.from(cleanBase64, 'base64');
        const reportFileName = fileName || `Audiometry_Report_${userName.replace(/\s+/g, '_')}_${reportId}.pdf`;

        const smtpConfig = getSMTPConfig();

        const htmlContent = `
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background-color: #0f172a; color: #f8fafc; border-radius: 16px; padding: 24px; border: 1px solid #334155;">
            <div style="text-align: center; padding-bottom: 20px; border-bottom: 1px solid #1e293b;">
                <h1 style="color: #f59e0b; margin: 0; font-size: 24px; letter-spacing: 1px;">SONIQX</h1>
                <p style="color: #94a3b8; margin: 4px 0 0 0; font-size: 12px; text-transform: uppercase; letter-spacing: 2px;">Precision Digital Audiology Platform</p>
            </div>

            <div style="padding: 20px 0;">
                <h2 style="color: #ffffff; font-size: 18px; margin-top: 0;">Official Clinical Hearing Screening Report</h2>
                <p style="color: #cbd5e1; font-size: 14px; line-height: 1.6;">Dear <strong>${userName}</strong>,</p>
                <p style="color: #cbd5e1; font-size: 14px; line-height: 1.6;">Please find attached your official digital audiometry screening report PDF generated by the SONIQX Audiology Platform.</p>

                <div style="background-color: #1e293b; border-radius: 12px; padding: 16px; margin: 20px 0; border: 1px solid #334155;">
                    <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
                        <tr>
                            <td style="color: #94a3b8; padding: 6px 0;">Report ID:</td>
                            <td style="color: #f8fafc; font-weight: bold; padding: 6px 0; text-align: right;">${reportId}</td>
                        </tr>
                        <tr>
                            <td style="color: #94a3b8; padding: 6px 0;">Screening Date:</td>
                            <td style="color: #f8fafc; font-weight: bold; padding: 6px 0; text-align: right;">${date}</td>
                        </tr>
                        <tr>
                            <td style="color: #94a3b8; padding: 6px 0;">Patient Name:</td>
                            <td style="color: #f8fafc; font-weight: bold; padding: 6px 0; text-align: right;">${userName}</td>
                        </tr>
                        <tr>
                            <td style="color: #94a3b8; padding: 6px 0;">Screening Status:</td>
                            <td style="padding: 6px 0; text-align: right;">
                                <span style="display: inline-block; padding: 4px 10px; border-radius: 6px; font-weight: bold; font-size: 12px; ${overallStatus === 'PASS' ? 'background-color: #064e3b; color: #34d399;' : 'background-color: #831843; color: #f472b6;'}">
                                    ${overallStatus}
                                </span>
                            </td>
                        </tr>
                        ${notes ? `
                        <tr>
                            <td style="color: #94a3b8; padding: 6px 0;">Clinical Notes:</td>
                            <td style="color: #f8fafc; padding: 6px 0; text-align: right;">${notes}</td>
                        </tr>
                        ` : ''}
                    </table>
                </div>
            </div>

            <div style="text-align: center; padding-top: 16px; border-top: 1px solid #1e293b; color: #64748b; font-size: 11px;">
                <p style="margin: 0;">Sent automatically via SONIQX Digital Audiology Platform</p>
                <p style="margin: 4px 0 0 0;">Sender: ${smtpConfig.smtp_user}</p>
            </div>
        </div>
        `;

        const mailOptions = {
            from: `"SONIQX Audiology Platform" <${smtpConfig.smtp_user}>`,
            to: cleanRecipient,
            subject: `[SONIQX AUDIOMETRY PDF REPORT #${reportId}] - ${userName}`,
            text: `Hello ${userName},\n\nPlease find attached your official digital audiometry screening report PDF.\n\nReport ID: ${reportId}\nDate: ${date}\nStatus: ${overallStatus}\n\nSent via SONIQX Digital Audiology Platform (${smtpConfig.smtp_user}).`,
            html: htmlContent,
            attachments: [
                {
                    filename: reportFileName,
                    content: pdfBuffer,
                    contentType: 'application/pdf'
                }
            ]
        };

        const transporter = createTransporter(smtpConfig);
        const info = await transporter.sendMail(mailOptions);

        return res.status(200).json({
            success: true,
            message: `Official Audiology PDF report successfully emailed to ${cleanRecipient}.`,
            messageId: info.messageId,
            recipient: cleanRecipient
        });
    } catch (err) {
        return res.status(400).json({
            success: false,
            error: err.message || 'Failed to send email report.',
            code: err.code || 'EMAIL_FAILED'
        });
    }
};
